### ISSUE TITLE
Some words are swapped

### ISSUE THREAD

**Issue by Oblique82** [gapmiss/kingdom-study-tools-for-obsidian#2]
Example: Matthew 12 v 34

"O generation G1081 of vipers, G2191 how G4459 can G1410 ye, G1410 being G5607 evil, G4190 speak G2980 good things? G18 for G1063 out G1537 the G3588 of G4051 abundance G4051 the G3588 of G2588 heart G2588 the G3588 mouth G4750 speaketh. G2980"

in this verse the words "the" and 'of' appear to be reversed - not just once but twice. it should say "...out of the abundance of the heart..."

I suspect there might be other instances of this and may be an issue with how the original verses were parsed and interleaved with the greek/hebrew Strong's references

are you able to help clarify this?

**Comment by Oblique82** [comment]
I found another example : 

1 Corinthians 1 v 4

I thank [[G2168]] my [[G3450]] God [[G2316]] always [[G3842]] on behalf, [[G4012]] your [[G5216]] for [[G1909]] the [[G3588]] grace [[G5485]] of [[G2316]] God [[G2316]] which [[G3588]] is given [[G1325]] you [[G5213]] by [[G1722]] Jesus [[G2424]] Christ; [[G5547]]

should read "always on your behalf"

**Comment by gapmiss** [comment]
@Oblique82 Yes, there are numerous swapped words in the database.

This is the original source: https://github.com/bibleforge/BibleForgeDB

I installed and use this DB locally w/ an app I created. I used that data for exporting in order to create the Obsidian vault. 

FYI, I've seen some errors also w/ the Strong's numbers.

**Comment by Oblique82** [comment]
ok what options do we have? I looks like the developer hasn't been active for several years...

**Comment by Oblique82** [comment]
is there any way we can run a code that ignore's strongs references in our text, and simply compares a reference king james text to this text and show differences eg swapped verses?

**Comment by gapmiss** [comment]
> is there any way we can run a code that ignore's strongs references in our text, and simply compares a reference king james text to this text and show differences eg swapped verses?

Yes, this is possible, but would take a bit of effort to write some code to do so. Unfortunately, I do not have time right now. I may consider it in the future.

I understand there are errors in the text, but I've never not been able to deduct the correct order and/or Strong's definition when encountering such errors.

**Comment by Oblique82** [comment]
ok thanks for looking into it. the workflow of having wikilinks to the
strongs references is unique and powerful. it would be great if we could
find a source text which overcomes this challenge

-Tim

**Comment by Oblique82** [comment]
I would be willing to put some funding behind this if you could help me recruit a programmer to help us.

I have zero programming experience unfortunately so I can't help with that side of things

- Tim

**Comment by gapmiss** [comment]
> I would be willing to put some funding behind this if you could help me recruit a programmer to help us. I have zero programming experience unfortunately so I can't help with that side of things - Tim

I actually may have found a solution. I'm working on scraping these pages (e.g. https://biblehub.com/text/luke/2-38.htm) and then I can re-create the markdown files with this version of the KJV w/ Strong's lexicon.

I hope to have something for you later today. If you find the results valuable, then I would gratefully accept a donation for my labor.

I will hopefully have something for you soon...

**Comment by Oblique82** [comment]
Definitely- keep me posted

- Tim

**Comment by gapmiss** [comment]
I have a script created to scrape `biblehub.com` and create the markdown.

https://biblehub.com/text/genesis/1-1.htm
https://biblehub.com/text/genesis/1-2.htm
https://biblehub.com/text/genesis/1-3.htm
https://biblehub.com/text/genesis/1-4.htm
https://biblehub.com/text/genesis/1-5.htm
https://biblehub.com/text/genesis/1-6.htm
https://biblehub.com/text/genesis/1-7.htm
https://biblehub.com/text/genesis/1-8.htm
https://biblehub.com/text/genesis/1-9.htm
https://biblehub.com/text/genesis/1-10.htm
https://biblehub.com/text/genesis/1-11.htm
https://biblehub.com/text/genesis/1-12.htm
https://biblehub.com/text/genesis/1-13.htm
https://biblehub.com/text/genesis/1-14.htm
https://biblehub.com/text/genesis/1-15.htm
https://biblehub.com/text/genesis/1-16.htm
https://biblehub.com/text/genesis/1-17.htm
https://biblehub.com/text/genesis/1-18.htm
https://biblehub.com/text/genesis/1-19.htm
https://biblehub.com/text/genesis/1-20.htm
https://biblehub.com/text/genesis/1-21.htm
https://biblehub.com/text/genesis/1-22.htm
https://biblehub.com/text/genesis/1-23.htm
https://biblehub.com/text/genesis/1-24.htm
https://biblehub.com/text/genesis/1-25.htm
https://biblehub.com/text/genesis/1-26.htm
https://biblehub.com/text/genesis/1-27.htm
https://biblehub.com/text/genesis/1-28.htm
https://biblehub.com/text/genesis/1-29.htm
https://biblehub.com/text/genesis/1-30.htm
https://biblehub.com/text/genesis/1-31.htm

The script takes about 1 second per each verse. There are 31102 verses, which is ~8.5 hours to scrape every verse. So, before I run the script, I wanted to ask you if there is anything formatting-wise you would like me to change.

Formatting that could be changed could include:
- alter/add/remove any of the front-matter YAML fields i.e. cssClasses, aliases, date, etc.
- change `heading` sizes i.e. `## 1` ← `### 1`
- add a footer with readily-available data i.e. organization name, link to website, copyright, etc.
- add line-return(`\n`)/spacing 
    - i.e. "### 1`\n\n`In the beginning..." ← "### 1`\n`In the beginning..."
- add navigation to previous/next chapters
    - this will take a bit more programming to re-factor my code to work and wanted to ask before I make the effort to do so.

Here is the markdown for Genesis 1:

```
---
cssClasses: lexicon
---

# Genesis 1

### 1
In the beginning [[H7225]] created [[H1254]] God [[H430]] - [[H853]] the heavens [[H8064]] and [[H853]] the earth [[H776]]

### 2
And the earth [[H776]] was [[H1961]] formless [[H8414]] and void [[H922]] and darkness [[H2822]] [was] over [[H5921]] the face [[H6440]] of the deep [[H8415]] And the Spirit [[H7307]] of God [[H430]] was hovering [[H7363]] over [[H5921]] the face [[H6440]] of the waters [[H4325]]

### 3
And said [[H559]] God [[H430]] let there be [[H1961]] light [[H216]] and there was [[H1961]] light [[H216]]

### 4
And saw [[H7200]] God [[H430]] - [[H853]] the light [[H216]] that [[H3588]] [it was] good [[H2896]] and divided [[H914]] God [[H430]] between [[H996]] the light [[H216]] and between [[H996]] the darkness [[H2822]]

### 5
And called [[H7121]] God [[H430]] the light [[H216]] day [[H3117]] and the darkness [[H2822]] He called [[H7121]] night [[H3915]] And there was [[H1961]] evening [[H6153]] and there was [[H1961]] morning [[H1242]] day [[H3117]] the first [[H259]]

### 6
And said [[H559]] God [[H430]] let there be [[H1961]] a firmament [[H7549]] in the midst [[H8432]] of the waters [[H4325]] and let it [[H1961]] divide [[H914]] between [[H996]] the waters [[H4325]] [and] the waters [[H4325]]

### 7
So made [[H6213]] God [[H430]] - [[H853]] the firmament [[H7549]] and He divided [[H914]] between [[H996]] the waters [[H4325]] that [were] [[H834]] under [[H8478]] the firmament [[H7549]] and [[H996]] the waters [[H4325]] that [were] [[H834]] above [[H5921]] the firmament [[H7549]] and it was [[H1961]] so [[H3651]]

### 8
And called [[H7121]] God [[H430]] the firmament [[H7549]] sky [[H8064]] And there was [[H1961]] evening [[H6153]] and there was [[H1961]] morning [[H1242]] day [[H3117]] the second [[H8145]]

### 9
And said [[H559]] God [[H430]] let be gathered together [[H6960]] the waters [[H4325]] under [[H8478]] the heavens [[H8064]] into [[H413]] place [[H4725]] one [[H259]] and let appear [[H7200]] the dry [land] [[H3004]] and it was [[H1961]] so [[H3651]]

### 10
And called [[H7121]] God [[H430]] the dry [land] [[H3004]] Earth [[H776]] and the collection [[H4723]] of the waters [[H4325]] He called [[H7121]] Seas [[H3220]] And saw [[H7200]] God [[H430]] that [[H3588]] [it was] good [[H2896]]

### 11
And said [[H559]] God [[H430]] let bring forth [[H1876]] the earth [[H776]] grass [[H1877]] the herb [[H6212]] [that] yields [[H2232]] seed [[H2233]] [and] the tree [[H6086]] fruit [[H6529]] [that] yields [[H6213]] fruit [[H6529]] according to its kind [[H4327]] whose [[H834]] seed [is] [[H2233]] in itself [[H5921]] on [[H776]] the earth [[H1961]] and it was [[H3651]]

### 12
And brought forth [[H3318]] the earth [[H776]] grass [[H1877]] the herb [[H6212]] [that] yields [[H2232]] seed [[H2233]] according to its kind [[H4327]] and the tree [[H6086]] [that] yields [[H6213]] fruit [[H6529]] whose [[H834]] seed [is] [[H2233]] in itself [[H4327]] according to its kind [[H7200]] and saw [[H430]] God [[H3588]] that [[H2896]]

### 13
And there was [[H1961]] evening [[H6153]] and there was [[H1961]] morning [[H1242]] day [[H3117]] the third [[H7992]]

### 14
And said [[H559]] God [[H430]] let there be [[H1961]] lights [[H3974]] in the firmament [[H7549]] of the heavens [[H8064]] to divide [[H914]] between [[H996]] the day [[H3117]] and between [[H996]] the night [[H3915]] and let them be [[H1961]] for signs [[H226]] and seasons [[H4150]] for days [[H3117]] and years [[H8141]]

### 15
And let them be [[H1961]] for lights [[H3974]] in the firmament [[H7549]] of the heavens [[H8064]] to shine [[H215]] upon [[H5921]] the earth [[H776]] and it was [[H1961]] so [[H3651]]

### 16
And made [[H6213]] God [[H430]] - [[H853]] two [[H8147]] lights [[H3974]] great [[H1419]] - [[H853]] the light [[H3974]] greater [[H1419]] to rule [[H4475]] the day [[H3117]] and [[H853]] the light [[H3974]] lesser [[H6996]] to rule [[H4475]] the night [[H3915]] and [He made] [[H853]] the stars [[H3556]]

### 17
And set [[H5414]] them [[H853]] God [[H430]] in the firmament [[H7549]] of the heavens [[H8064]] to shine [[H215]] upon [[H5921]] the earth [[H776]]

### 18
and to rule [[H4910]] over the day [[H3117]] and over the night [[H3915]] and to divide [[H914]] between [[H996]] the light [[H216]] and between [[H996]] the darkness [[H2822]] And saw [[H7200]] God [[H430]] that [[H3588]] [it was] good [[H2896]]

### 19
And there was [[H1961]] evening [[H6153]] and there was [[H1961]] morning [[H1242]] day [[H3117]] the fourth [[H7243]]

### 20
And said [[H559]] God [[H430]] let abound [[H8317]] the waters [[H4325]] with an abundance [[H8318]] of creatures [[H5315]] living [[H2416]] and birds [[H5775]] let fly [[H5774]] above [[H5921]] the earth [[H776]] across [[H5921]] the face [[H6440]] of the firmament [[H7549]] of the sky [[H8064]]

### 21
So created [[H1254]] God [[H430]] - [[H853]] sea creatures [[H8577]] great [[H1419]] and [[H853]] every [[H3605]] thing [[H5315]] living [[H2416]] that moves [[H7430]] with which [[H834]] abounded [[H8317]] the waters [[H4325]] according to their kinds [[H4327]] and [[H853]] every [[H3605]] bird [[H5775]] winged [[H3671]] according to its kind [[H4327]] And saw [[H7200]] God [[H430]] that [[H3588]] [it was] good [[H2896]]

### 22
And blessed [[H1288]] them [[H853]] God [[H430]] saying [[H559]] Be fruitful [[H6509]] and multiply [[H7235]] and fill [[H4390]] - [[H853]] the waters [[H4325]] in the seas [[H3220]] and birds [[H5775]] let multiply [[H7235]] on the earth [[H776]]

### 23
And there was [[H1961]] evening [[H6153]] and there was [[H1961]] morning [[H1242]] day [[H3117]] the fifth [[H2549]]

### 24
And said [[H559]] God [[H430]] let bring forth [[H3318]] the earth [[H776]] the creature [[H5315]] living [[H2416]] according to its kind [[H4327]] livestock [[H929]] and creeping thing [[H7431]] and beast [[H2416]] of the earth [[H776]] [each] according to its kind [[H4327]] And it was [[H1961]] so [[H3651]]

### 25
And made [[H6213]] God [[H430]] - [[H853]] the beast [[H2416]] of the earth [[H776]] according to its kind [[H4327]] and [[H853]] livestock [[H929]] according to its kind [[H4327]] and [[H853]] everything [[H3605]] that creeps on [[H7431]] the earth [[H127]] according to its kind [[H4327]] and saw [[H7200]] God [[H430]] that [[H3588]] [it was] good [[H2896]]

### 26
And said [[H559]] God [[H430]] let Us make [[H6213]] man [[H120]] in Our image [[H6754]] according to Our likeness [[H1823]] and let them rule [[H7287]] over the fish [[H1710]] of the sea [[H3220]] and over the birds [[H5775]] of the air [[H8064]] and over the livestock [[H929]] and over all [[H3605]] the earth [[H776]] and over every [[H3605]] creeping thing [[H7431]] that creeps [[H7430]] on [[H5921]] the earth [[H776]]

### 27
So created [[H1254]] God [[H430]] - [[H853]] man [[H120]] in His [own] image [[H6754]] in the image [[H6754]] of God [[H430]] He created [[H1254]] him [[H853]] male [[H2145]] and female [[H5347]] He created [[H1254]] them [[H853]]

### 28
And blessed [[H1288]] them [[H853]] God [[H430]] and said [[H559]] to them [[H430]] God [[H6509]] Be fruitful [[H7235]] and multiply [[H4390]] and fill [[H853]] - [[H776]] the earth [[H3533]] and subdue it [[H7287]] and have dominion [[H1710]] over the fish [[H3220]] of the sea [[H5775]] and over the birds [[H8064]] of the air [[H3605]] and over every [[H2416]] living thing [[H7430]] that moves [[H5921]] upon [[H776]]

### 29
And said [[H559]] God [[H430]] behold [[H2009]] I have given [[H5414]] you [[H853]] - [[H3605]] every [[H6212]] herb [[H2232]] [that] yields [[H2233]] seed [[H834]] which [is] [[H5921]] on [[H6440]] the face [[H3605]] of all [[H776]] the earth [[H853]] and [[H3605]] every [[H6086]] tree [[H834]] which [[H6529]] in [it] [[H6086]] [is] the fruit [[H2232]] of a tree [[H2233]] yielding [[H1961]] seed [[H402]]

### 30
And to every [[H3605]] beast [[H2416]] of the earth [[H776]] and to every [[H3605]] bird [[H5775]] of the air [[H8064]] and to everything [[H3605]] that creeps [[H7430]] upon [[H5921]] the earth [[H776]] which [has] [[H834]] in it [[H5315]] the breath [[H2416]] life [[H853]] - [[H3605]] [I have given] every [[H3418]] green [[H6212]] herb [[H402]] for food [[H1961]] and it was [[H3651]]

### 31
And saw [[H7200]] God [[H430]] - [[H853]] everything [[H3605]] that [[H834]] He had made [[H6213]] and indeed [[H2009]] [it was] good [[H2896]] very [[H3966]] and there was [[H1961]] evening [[H6153]] and there was [[H1961]] morning [[H1242]] day [[H3117]] the sixth [[H8345]]
```

**Comment by gapmiss** [comment]
I would also take a look at the verses mentioned earlier in this conversation, and compare them and see if you are satisfied that biblehub.com's version is more suitable for your needs.

**Comment by Oblique82** [comment]
Firstly thank you so much for helping with this project.

Where can I donate to it?

Secondly before we explore aesthetic optimisations, YAML etc, there still appears to be a problem with the script and how the text is parsed.

Eg Genesis 1:11 the 5th row from the bottom has no strong's source number, and as a result, words after this have the wrong strong's number applied to them, (they 'lose synchronisation with the English') and the final word 'so' is missing (the sentence is incomplete)

Verse 30 also has this issue, and the last word is skipped (where 10th row from the bottom has no Strong's number)

We would need to find a way to make the parser resilient to these missing words and correctly re-sync the text after skipping these


- Tim

**Comment by gapmiss** [comment]
OK, I see where the errors occur. You can see on this page where the phrase (in itself) has no Strong's number associated. https://biblehub.com/text/genesis/1-11.htm Let me figure out how I'm going to account for that. Excellent eyes/testing on your part.

**Comment by gapmiss** [comment]
Tim,
The current script cannot handle the missing Strong's numbers, so I went looking for better data. I found another biblehub site that has the Berean Study Bible w/ Strong's. [Gen 1:1](https://openbible.com/strongs/genesis/1-1.htm) [Matt 1:1](https://openbible.com/strongs/matthew/1-1.htm)

The script took very little altering to get it to parse the different site. There are some empty nums but I'm able to parse those out and replace them. Currently, I've only found that the OT has empty nums, ~227 empty in the book of Gen.  For now, I've replaced them w/ `H0000`.

Markdown for Genesis & Matthew: [gen-matt.zip](https://github.com/gapmiss/kingdom-study-tools-for-obsidian/files/9376252/gen-matt.zip)

Take a look and let me know what you think.

---

CSS Snippet for the unresolved `[[H0000]]` links:

```css
a.is-unresolved {
	color:FireBrick !important;
	opacity: 100% !important;
	border: 3px solid Lime !important;
	font-size:xx-large !important;
}
```

**Comment by Oblique82** [comment]
Thanks for the update -

I have imported it to my vault

1. Well done with all your scripting skills! Especially that you were able to adapt them for a different website. This is amazing work!!!
2. Just to be clear, are the lexicons themselves rock solid/accurate (eg correct Strong’s number always applies to the correct definition?) I am not sure how these were generated
3. I have compared Strongs concordances between "open bible" and "bible hub”- it looks like the numbers missing on bible hub are the same ones missing on open bible, and the ONLY reflect Hebrew pronouns and prepositions
4. For your script, I can see that the H0000 simply replace the absence of Strongs numbers that don’t exist in the source on the website. It may be that there are no strong’s numbers for these common pronouns/prepositions in Hebrew
5. Therefore… I wonder if for reading fluidity we consider the executive decision: removing them all together? Eg so the text flows on without the “H0000 insertions"
6. Note: Biblehub website has several translations available - is there no way to use KJV with Strongs reference? Bit of a long shot I think - however it would still be nice to make this work with KJV for copyright distribution ease.
7. Also there are some key examples where KJV has a very different meaning from other translations (eg “Us" vs "Them," https://www.biblestudytools.com/revelation/5-10-compare.html)


What do you think? Also you never told me how I can donate :)

- Tim

**Comment by gapmiss** [comment]
Tim,

> 1. Well done with all your scripting skills! Especially that you were able to adapt them for a different website. This is amazing work!!!

Thank you, appreciate it.

> 2. Just to be clear, are the lexicons themselves rock solid/accurate (eg correct Strong’s number always applies to the correct definition?) I am not sure how these were generated

Yes, I checked a handful of verses and they were accurate.

The 2 books I sent you were generated from:

https://openbible.com/strongs/genesis/1-1.htm
...
https://openbible.com/strongs/matthew/1-1.htm
...and so on.

> 3. I have compared Strongs concordances between "open bible" and "bible hub”- it looks like the numbers missing on bible hub are the same ones missing on open bible, and they ONLY reflect Hebrew pronouns and prepositions (they, them, to, for, us etc)
> 4. For your script, I can see that the H0000 simply replaces the absence of Strongs numbers that don’t exist in the source on the website. It may be that there are no strong’s numbers for these common pronouns/prepositions in Hebrew
> 5. Therefore… I wonder if for reading fluidity we consider the executive decision: removing them all together? Eg so the text flows on without the “H0000 insertions"

Yes, agree, and I would remove them for readability.

> 6. Note: Biblehub website has several translations available - is there no way to use KJV with Strongs reference? Bit of a long shot I think - however it would still be nice to make this work with KJV for copyright distribution ease. I do think this translation is much easier to read in native English without the words being reversed in the earlier example
> 7. Also there are some key examples where KJV has a very different meaning from other translations (eg “Us" vs "Them," https://www.biblestudytools.com/revelation/5-10-compare.html)

Yes, biblehub has a KJV Strongs version here: https://openbible.com/kjvs/genesis/1.htm

At fist glance, the HTML structure/CSS classing is very different and it will be more difficult to parse and will require a different approach. IOWs, I'd have to do some research/testing on if/how to parse this structure and implement via mostly new code.

> 8. for finalising this project, eg YAML, headings, chapter forward and back, I really liked the way you originally set them out in Kingdom study tools and also really liked the Bible note.md and chapter note index files (like maps of content for each book)

I can implement the original structure irregardless of what Bible version.

> Also you never told me how I can donate :)

Do you have Venmo or Cash App? and possibly PayPal (try to avoid the business fees)


- Chris

**Comment by Oblique82** [comment]
Good ideas

I think for now let's finalise this part of the project with berean study Bible translation - with h0000 removed - it should be a good reading experience

I can use PayPal if can you PM me on GitHub or are you happy to share it here ?

- Tim

**Comment by gapmiss** [comment]
I do not see a way to PM you, so I have published a private note here:

https://noteshare.space/note/cl70w4vei125701r4ziqc6fm2#vUBw3J58C3FPaJboazoNMagdeCr3df_V-oCUJFlGQoQ

After viewing, let me know, and I will remove this comment. Thank you

**Comment by Oblique82** [comment]
Ok thanks I have saved this - happy for you to remove standby

- Tim

**Comment by Oblique82** [comment]
Awesome - I'm just glad i was able to explain it clearly enough :)

- Tim
